#!/bin/csh

# Note: must install python and freesurfer first
# https://www.anaconda.com/distribution/#download-section
# https://surfer.nmr.mgh.harvard.edu/fswiki/DownloadAndInstall

source ./venv/bin/activate

python3 TMS_EEG_GUI.py